controllers:
    resource: ../../src/Controller/
    type: annotation

product_controllers:
    resource: ../../src/Product/Infrastructure/Controller/
    type: annotation

shared_controllers:
    resource: ../../src/Shared/Infrastructure/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
